# -*- coding: utf-8 -*-
"""Mejoras escritas a mano: S09 a S16."""

HAND = {
"S09": [
"Nuevas fuentes: MOOCs de universidades, gobierno (Chile y LatAm), vendors (Cisco, Oracle, Google, etc.) con template de import.",
"Monitor de salud: chequeo diario de URLs (200 + texto clave) con alerta si un enlace muere o cambia.",
"Deteccion automatica de programas nuevos (diff de contenido + senales) con verificacion antes de agregar.",
"Cada oferta con 'nivel de verificacion' (oficial, prensa, comunidad) y fecha visible en la tarjeta.",
"Archivo automatico de ofertas expiradas con historial (que las reemplazo).",
"Catalogo de ofertas locales (SENCE, universidades, municipios) con ventana de postulacion.",
"Deteccion de cambios de condicion (precio, plazo) con changelog por oferta.",
"Vista 'catalogo por meta': filtrado por puesto objetivo, no por vendor.",
"Comunidad: reportar enlace roto con un toque y verificacion antes de corregir (con credito al que lo reporte).",
"Import de nuevas fuentes en YAML: agregar una fuente en 5 minutos sin tocar codigo.",
"Ranking de fuentes por rendimiento: ofertas validas encontradas y utiles para el perfil.",
"Idioma (es o en) auto-detectado por fuente y mostrado en la tarjeta.",
"'Que hay de nuevo esta semana' en el catalogo, con diff visual de las tarjetas.",
"De-duplicacion: si dos fuentes ofrecen la misma cert, se une la tarjeta y se muestran ambas fuentes.",
],
"S10": [
"Asistente central de becas: cada beca con requisitos, ventana y estado de postulacion del usuario.",
"Coursera: postulacion de financial aid guiada, con carta borrador adaptada al perfil (editable).",
"SENCE: cursos gratis con fechas y alertas de apertura de postulacion.",
"Postulacion directa a SENCE con ClaveUnica, paso a paso con capturas.",
"Estatus estudiantil: gestion de carnet y vigencia para usarlo en todos los beneficios.",
"Becas locales: base de becas chilenas (estado, universidades, fundaciones) con ventanas y requisitos.",
"CORFO y programas laborales: deteccion de programas que financian capacitacion o certificacion.",
"Cursos gratis de universidades: MOOCs y programas de U. de Chile, U. de Concepcion, PUC y otras.",
"Dector de 'semanas gratis': cursos gratis por tiempo limitado, con expiracion verificada.",
"Municipios: cursos municipales (Biobio y otras regiones) con registro y fechas.",
"Carta de postulacion generada automaticamente por beca, desde el perfil (motivo, situacion, objetivo).",
"Calendario de becas: ventanas, plazos y probabilidad (por cumplimiento de requisitos).",
"Plan B de beca: si no aprueba, la alternativa mas barata (descuento, voucher, instalments) verificada.",
"Deteccion de ofertas 'solo residentes' (por ejemplo 'gratis solo en Chile') con verificacion de elegibilidad.",
],
"S11": [
"Postulacion directa: cada tarjeta 100% gratis lleva con 'Postular ahora' a la pagina real del formulario.",
"Asistente de postulacion: el formulario se completa con los datos del perfil (auto-fill, confirmable).",
"Tracker de estado: postulado, confirmado, admitido, enrolado, con fecha y captura de cada cambio.",
"Email de confirmacion: guia local (en que bandeja buscarlo) para detectar la confirmacion rapido.",
"Trampas de onboarding documentadas por plataforma (por ejemplo 'Credly con el mismo email de la postulacion').",
"Onboarding por plataforma (UoPeople, Coursera, edX, mylearn, SkillBuilder): primeros pasos con capturas.",
"Si la postulacion se rechaza: motivo probable + siguiente opcion (re-postular, otra cert, otra beca).",
"'Acceso': donde entra el curso cuando se aprueba, con enlace directo guardado en la tarjeta.",
"Sugerencia de email dedicado para certificaciones, con plantilla de creacion.",
"Checklist de datos personales (RUT, foto de ID, carnet estudiantil) para no perder tiempo en formularios.",
"Historial de postulaciones (todas, con estado) en una sola pantalla.",
"'Paquete de postulacion': CV, carta y enlaces listos para pegar en cada formulario.",
"Deteccion de ventanas de postulacion ('abiertas hasta X') con countdown.",
"Deteccion de lista de espera y alerta cuando aperece cupo.",
],
"S12": [
"Panel 'Mis certificaciones': todas con estado (en curso, aprobada, badge activo, por renovar, vencida).",
"Verificacion automatica: badge en Credly o LinkedIn con enlace publico guardado.",
"Renovaciones: countdown y guia de recertificacion cuando aplique.",
"'Prueba de avance': reporte semanal exportable (horas, simulacros, hitos).",
"Transcript local: listado cronologico de todo lo hecho, usable en entrevista.",
"Fotografia o PDF de cada certificado, con metadatos (fecha, emisor, enlace de verificacion).",
"Dector de gaps: que le falta al usuario para el puesto objetivo (comparado con ofertas reales).",
"Avance por area (ciber 60 por ciento, datos 20 por ciento) con grafica de radar.",
"'Dias sin actividad' con reactivacion suave (plan de 7 dias, sin culpa).",
"Hitos automaticos: badges de progreso (10 h, 50 h, 100 h, 1ra cert, 3ra cert).",
"Sincronia con el plan: si el avance real va atrasado, alerta y re-plan en un toque.",
"'Prueba de esfuerzo' para entrevista: horas, proyectos y simulacros realizados, exportable.",
"Valididad de cada cert (si caduca y en cuanto tiempo) visible en la tarjeta.",
"'Antes y despues': comparacion del CV inicial contra el actual, lado a lado.",
],
"S13": [
"Generador de CV ATS desde certificaciones + proyectos, en español e inglés.",
"Version del CV por oferta: keywords auto-adaptadas a la oferta detectada.",
"Portafolio personal (web en Pages) con badges, proyectos y certificados, con enlace unico.",
"Asistente de LinkedIn: secciones (certificaciones, skills, 'acerca de') con texto borrador.",
"Al aprobar una cert: actualizar CV + LinkedIn + portafolio en un toque (editable antes de guardar).",
"Perfil de GitHub o GitLab: README con certificaciones y proyectos (template).",
"'Impacto' de cada cert en el CV: no solo el nombre, sino que demuestra (skill verificable).",
"CV con QR que lleva al portafolio.",
"Asistente de proyectos: 3 proyectos de portafolio por area, paso a paso y con demo publica.",
"Carta de presentacion por oferta, con texto adaptado (borrador automatico, editable).",
"'Que decir en la entrevista' por cert: version de 1 minuto y de 3 minutos.",
"Check de CV: coherencia (fechas, nombres exactos de certs, sin typos).",
"Historico de versiones del CV (v1, v2) con diff entre versiones.",
"Paquete descargable en un toque (CV + portafolio + carta, PDF).",
],
"S14": [
"Buscador de empleo local (Puyal, LinkedIn, Computrabajo, BNE) con filtros por certificacion.",
"Alerta de empleo: ofertas nuevas que matchean el perfil, resenas diarias.",
"Match: cada oferta puntuada por su correspondencia con las certificaciones del usuario.",
"Tracker de postulaciones laborales: oferta, postulado, entrevista, respuesta, en kanban.",
"Salario benchmark local (Chile y remoto) con fuente y fecha actualizada.",
"'CV minimo viable' de junior: que se necesita para conseguir la primera entrevista.",
"Banco de preguntas de entrevista por area y nivel, en español e inglés, con respuesta modelo.",
"Entrevista simulada: preguntas grabadas con auto-evaluacion de la respuesta.",
"Analisis de N ofertas reales: que piden (keywords, certs) frente a que tiene el usuario.",
"Remoto: guia de busqueda (zona horaria, pago en USD, contrato, impuestos en Chile).",
"Red: meetups y comunidades locales (Biobio, Santiago) con agenda y registro.",
"Plan '30 dias a la primera entrevista': accion concreta por dia.",
"Follow-up: recordatorio de seguimiento de postulaciones (a los 7 y 14 dias).",
"Evaluacion de oferta: checklist (salario, crecimiento, remoto, tipo de contrato).",
],
"S15": [
"Grupo de estudio local: invitar a un amigo a compartir plan y ver el avance mutuo (con permiso).",
"Accountability: 1 persona ve las metas semanales del usuario (privado, opt-in).",
"Meetups locales: agenda de meetups tech (Biobio, Santiago) con registro.",
"Discord o Telegram: lista de grupos activos por area con reglas de entrada.",
"'Estudia conmigo': timer local para sesiones virtuales con un buddy.",
"Meta publica (opcional): publicar el hito para recibir apoyo.",
"Mentores locales: directorio (voluntario) con disponibilidad.",
"Compartir reporte: PDF semanal para enviar al buddy de accountability.",
"Retos por meses (por ejemplo '100 h de estudio') con ranking privado.",
"Comunidad de 'primeras entrevistas': log de procesos y aprendizajes (anonimo).",
"Universidades (U. de Concepcion, U. de Chile, otras): grupos de estudiantes gratis para estudiar.",
"Intercambio de notas: compartir y recibir flashcards o resenas por certificacion.",
"Check-in semanal (5 min) con el buddy, con agenda y recordatorio.",
"Privado por default: nada se comparte sin permiso explícito.",
],
"S16": [
"Recordatorios inteligentes por fechas reales (plazos, ventanas, examenes) con T-7, T-3, T-1 y T-0.",
"Escala: si un recordatorio se ignora, se repite y propone nueva fecha.",
"Pantalla 'Hoy': que queda pendiente hoy (estudio, postulacion, plazo) en un solo lugar.",
"Recordatorio semanal (domingo): plan de la semana generado desde el roadmap.",
"Alerta de deadline con severidad (rojo, naranja, verde).",
"Notificacion local en Android (widget) sin abrir la app.",
"Snooze y 'lo hago ahora' directo desde la notificacion.",
"Horas silenciosas: sin notificaciones de noche salvo lo critico.",
"'No me dejes perder la ventana': chequeo diario de SENCE y becas antes del cierre.",
"Digest opcional (1 vez al dia): las 3 novedades mas relevantes para el perfil.",
"Alerta de examen con paquete (que llevar, donde entrar, a que hora).",
"Alerta de renovacion de certs (60, 30 y 7 dias antes del vencimiento).",
"Alerta '30 dias sin actividad' con plan de reactivacion.",
"Todas las notificaciones locales (sin servidor) con override manual.",
],
}
