# -*- coding: utf-8 -*-
"""Mejoras escritas a mano: S17 a S26."""

HAND = {
"S17": [
"100 por ciento offline: catalogo, plan, simulacros y notas funcionan sin internet.",
"Packs offline por certificacion (descarga bajo demanda, con limite de espacio).",
"Sincronizacion de datos: los cambios hechos offline se integran al volver a tener red.",
"Privacidad local: todos los datos en el dispositivo; export opcional cifrado.",
"Sin cuentas, sin tracking, sin ads (uso personal, datos se quedan en el telefono).",
"Backup en un toque (JSON cifrado) hacia la nube del propio usuario.",
"Restore desde backup con verificacion (hash) para detectar corrupcion.",
"Rendimiento: arranque en menos de 1 s y busqueda local en menos de 200 ms (medido en CI).",
"Modo bajo consumo: sin animaciones en background, para bateria limitada.",
"Espacio reducido: limpieza de packs descargados con politica de retencion.",
"Seguridad: opcion de PIN o biometrico para abrir la app.",
"'Borrar todo': borrado real con doble confirmacion (derecho al olvido).",
"Auditoria de privacidad: pantalla que muestra que datos guarda la app y donde.",
"Red inestable: reintentos automaticos con backoff y cola visible de operaciones.",
],
"S18": [
"Widget en la portada del telefono: meta de hoy + proxima accion + countdown al examen.",
"Quick tiles (ajustes rapidos de Android): 'estudiar ahora' (arranca pomodoro).",
"Iconos de app con anillo de progreso (porcentaje de la cert actual).",
"PWA: instalable en telefono y escritorio, con shortcuts.",
"Modo oscuro por sistema + manual.",
"Tamano de texto ajustable (accesibilidad) y alto contraste.",
"Ojiva y tableta: layout de 2 columnas (plan + estudio).",
"Atajos de teclado (escritorio): busqueda, proxima accion, snooze.",
"Sonido local (sin audio externo) para estudio y celebraciones.",
"'Hoy' en un gesto (swipe) desde cualquier pantalla.",
"Recientes: ultimas 5 acciones con regreso directo.",
"Modo inmersivo (fullscreen) para sesiones de estudio.",
"Version lite (menos peso) para telefonos antiguos (sin simulacros pesados).",
"Guia de instalacion PWA en navegadores comunes (Chrome, Safari, Edge).",
],
"S19": [
"Copiloto local: preguntas y respuestas sobre el catalogo, el plan y las notas.",
"'Planea mi semana': genera el calendario de estudio desde la disponibilidad real.",
"CV por lenguaje natural: generar e iterar ('hazlo mas de datos', 'acortalo a 1 pagina').",
"Cartas: borrador por beca o por oferta, con tono formal y datos del perfil.",
"Entrevista: genera preguntas segun la oferta real (pegar la descripcion).",
"'Explícame': cada tema del temario en 3 niveles (basico, medio, avanzado).",
"'Pregúntame': preguntas instantaneas sobre lo estudiado hoy.",
"Resumenes: modulo o documento largo a 10 puntos clave.",
"'Estoy listo?': evaluacion con simulacros y responde con honestidad (con datos).",
"Deteccion de derivacion: si el usuario estudia fuera de plan, propone re-ajuste.",
"'Los 3 siguientes pasos mejores' con el motivo de cada uno.",
"Modo local (sin nube) por default; si usa nube, visible y opt-in.",
"Historial de conversaciones por tema (buscable).",
"Anti-halucinacion: cada respuesta cita el catalogo o una fuente con fecha (nada inventado).",
],
"S20": [
"Racha de dias de estudio (con tolerancia: 1 semana al mes no rompe la racha).",
"Niveles por area (0 a 10) con criterios visibles (horas, simulacros, certs).",
"Hitos: primera cert, 10 h, 50 h, 100 h, primera entrevista, primera oferta.",
"Pantalla 'Progreso': que cambio este mes (antes y despues).",
"Recompensa (personal): cuando se llega a un hito, el usuario define la recompensa.",
"XP visual por area (radar) y 'dias para la meta'.",
"'Prueba de inicio': comparar semana 1 con semana N.",
"Retos por semanas (opcional, solo contra uno mismo).",
"'Sin verguenza': si se rompe la racha, se reinicia sin perder historial.",
"Badge de constancia (3 meses activos, 6 meses activos).",
"'Muro de avance': linea de tiempo visual de todo lo logrado.",
"Ranking privado (local): yo contra mi historico.",
"Celebracion: al aprobar un examen, pantalla de 10 segundos (sin spam).",
"Meta semanal visible: horas objetivo vs horas reales, con color (verde, amarillo).",
],
"S21": [
"Auto-auditoria: la app chequea sus enlaces, datos y rendimiento, y propone correcciones.",
"Changelog visible: que mejoro y cuando (en la app y en el repo).",
"Tracker de roadmap: las 1000 mejoras de este documento como lista maquina (JSON) con estado.",
"Prioridad automatica: ordenar las 1000 mejoras por impacto y evidencia (no por intuicion).",
"Feedback: el usuario puntua cada pantalla (pulgar), y la app detecta puntos debiles.",
"Experimentos: A/B local (2 variantes de una pantalla) con metrica (tiempo a la accion).",
"'Que hacer a continuacion': el motor propone 3 mejoras implementables (con diff o PR).",
"Monitor de enlaces 24/7 (via CI): si un enlace muere, se abre issue y se corrige.",
"Calidad de datos: verificacion semanal de que todo descuento tenga fuente real.",
"Deteccion de nuevas fuentes (web) y propuesta de incorporacion (con verificacion).",
"Rendimiento: medicion semanal (arranque, busqueda) con alerta de regresion.",
"Post-mortem semanal: que no funciono (pantallas, busquedas sin resultado) y accion.",
"Roadmap publico (repo) con estado por mejora (pendiente, en curso, lista).",
"'Version del objetivo': cada mes, re-preguntar si el objetivo principal sigue siendo el mismo y ajustar.",
],
"S22": [
"Reporte semanal (PDF): horas, avance, simulacros, deadlines.",
"Reporte mensual: que se consiguio, que falta, plan del mes siguiente.",
"'Prueba' para entrevista: 1 pagina con horas, certs, proyectos y fechas.",
"Export de datos (JSON o CSV): todo, sin lock-in.",
"KPIs: constancia, avance, dias para la meta, en una pantalla.",
"Tendencia: horas por semana (6 meses) con alerta de caida.",
"'Costo real' del plan (debe ser $0): muestra el gasto efectivo del usuario.",
"Reporte para mentor (opcional, privado, 1 pagina).",
"'Estado de mis certs': validas, por renovar, vencidas (1 pantalla).",
"'Estado de mis postulaciones': todas con estado y proxima accion.",
"Dashboard simple con los 5 numeros que importan.",
"'Año en revision' (diciembre): que se logro, que se dejo, plan siguiente.",
"Comparativo: inicio vs actual (CV, skills, certs, salario).",
"Reporte en español e inglés (mismos datos) para procesos remotos.",
],
"S23": [
"Test E2E: flujos criticos del usuario (buscar, postular, estudiar, rendir).",
"Link checker en CI: todas las URLs del catalogo (status + texto clave).",
"Test de datos: todo descuento con fuente verificable (cero fantasmas).",
"Accesibilidad: WCAG AA (contraste, lector de pantalla, foco visible).",
"Rendimiento: Lighthouse sobre 90 (PWA) y arranque menor a 1 s (Android).",
"Reporte de crashes (local, sin PII) con pasos de reproduccion.",
"Test en dispositivo real (2G/3G, almacenamiento bajo, Biobio).",
"Regresion: cada push corre toda la bateria (CI existente, expandirla).",
"Test visual: screenshots por pantalla (detectar rompida visual).",
"Test de datos: de-duplicacion, orden y categoria del catalogo.",
"'Smoke' de 10 segundos para el usuario (boton 'probar la app').",
"Canary: backup de datos antes de cambios grandes, con rollback.",
"Metrica de exito (north star): por ciento de semanas con plan completado.",
"Tests publicos (repo) con reporte legible por humanos.",
],
"S24": [
"Primer arranque: asistente de 3 minutos (meta, horas, nivel) con defaults sensatos.",
"Ayuda local (FAQ) por pantalla, buscable.",
"'Como se hace' por video corto (aplicar, beca, examen) para los flujos criticos.",
"Glosario: proctoring, temario, financial aid, ClaveUnica, voucher, un solo uso (en español).",
"'Que es esta pantalla' (1 toque de informacion en cada pantalla).",
"Onboarding de cada plataforma (UoPeople, Coursera, mylearn) con capturas.",
" Tutorial local (Chile): SENCE, ClaveUnica, BNE paso a paso.",
"Checklist de 'los primeros 7 dias' con marcado de completado.",
"Docs (repo) con arquitectura y decisiones (para que el usuario mantenga la app).",
"'Hojita de trucos' del plan (1 pagina) imprimible.",
"Ayuda sin internet (todo local).",
"'Reportar un problema' (local, con contexto, sin PII).",
"Version de docs (changelog por version de la app).",
"Modo 'mentor': guia para explicar la app a una tercera persona.",
],
"S25": [
"Multi-dispositivo (opcional, cifrado): telefono + escritorio en sincronia.",
"Otros paises: template para adaptar a Peru, Colombia y Mexico (beneficios locales).",
"Multi-usuario (familia o amigos) con perfiles privados.",
"Modo mentor: 1 usuario guia a otros (local, gratis).",
"Aportar a la comunidad: compartir fuentes verificadas (con credito).",
"Sostenibilidad: costo 0 de mantener (CI gratis, open source).",
"'Fork personal': el usuario puede forkear el repo y personalizar (guia).",
"Roadmap abierto: cualquiera (el usuario) propone mejoras con una plantilla.",
"Archivo: versiones antiguas de datos (historial de ofertas) consultable.",
"'Certf 2.0': vision del proximo ano en 1 pagina (objetivo, hitos, metrica).",
"Medicion de exito: por ciento de semanas con plan completado (publico en repo).",
"'Legacy': si el usuario se detiene, sus datos son exportables y su portafolio vive.",
"Open source (ya lo es): licencia y contribucion claras.",
"'Si se logra el objetivo': plan de mantenimiento (renovaciones, nueva meta).",
],
"S26": [
"Pantalla 'Hoy' global: las 3 cosas mas importantes del dia (estudiar, postular, deadline) en 1 lugar.",
"Busqueda unica global (catalogo + notas + CV + ofertas) con secciones en el resultado.",
"Modo '10 minutos': cuando solo hay 10 min, la app muestra exactamente que hacer con ese tiempo.",
"El campo 'examen' del catalogo alimenta simulacros, plan, logistica y CV (1 sola fuente de verdad).",
"Coherencia de idioma: toda la app en español (export en inglés), sin jerga innecesaria.",
"Politica anti-fantasma visible: toda pantalla con oferta muestra la fecha de verificacion.",
"Atajos numericos globales: 1 (hoy), 2 (plan), 3 (buscar), 4 (examen), 5 (reporte).",
"Voz (español): decir 'que sigue?' y la app responde con la accion.",
"'Semana en revision' cada domingo (5 min): logros, atrasos, plan.",
"'Mes en revision' (15 min): hitos, metodo, ajuste del mes.",
"Todo lo que cuesta dinero es opcional: el nucleo es $0.",
"Modo enfoque: apaga notificaciones salvo examen y deadlines.",
"Modo recuperacion: despues de 2 semanas fuera, plan de 7 dias para volver sin culpa.",
"Datos: 1 solo store local (JSON) versionado, con migraciones al actualizar.",
"'Donde lo deje': la app guarda el punto pendiente y retoma donde estaba.",
"'Foto de inicio' del ano: snapshot de los datos al inicio (para comparar).",
"Plan intensivo '100 dias' (3 fases) para un objetivo puntual.",
"La 'estrella polar' visible: el objetivo (puesto, mes, salario) siempre en la cabecera.",
],
}
