# -*- coding: utf-8 -*-
"""Mejoras escritas a mano: S01 a S08."""

HAND = {
"S01": [
"P0::Agregar el campo 'examen' (tipo de test: opcion multiple, laboratorio, oral, proyecto, portafolio, coding) a cada certificacion del catalogo, y adaptar ruta, plan y preparacion al tipo real de examen.",
"P0::Perfil personal local (puesto objetivo, nivel actual, horas reales por semana, idioma) que reordena el catalogo y genera el plan 0 a PRO personal.",
"P0::Boton 'Siguiente accion' unico en la portada: siempre muestra exactamente que hacer ahora (postular, estudiar, simulacro, agendar examen, actualizar CV).",
"P0::Plan semanal de estudio automatico con bloques realistas (turno, commute) y re-agendado automatico si se pierde un bloque.",
"P0::Motor de simulacros por tipo de test: opcion multiple con feedback inmediato, laboratorio con sandbox, defensa oral con simulador, portafolio con rubrica.",
"P0::Bitacora de errores: cada falla en simulacro queda guardada por tema, con repaso espaciado y export a Anki o flashcards del telefono.",
"P0::Asistente de dia de examen: checklist T-7 a T-0, documentos, proctoring, prueba de sistema y contingencia (que hacer si todo falla).",
"P0::Post-examen: registro automatico del resultado, politica y descuento de retake (fuente oficial) y actualizacion del panel 'Mis certificaciones'.",
"P0::Portafolio personal verificable (web) con badges, proyectos y certificados, con enlace unico para pegar en CV y LinkedIn.",
"P0::Generador de CV 0 a PRO (ATS, español e inglés) desde certificaciones + proyectos, con version por oferta y tracking de postulaciones.",
"P0::Preparacion de entrevistas: banco de preguntas por area y nivel (junior a senior) en español e inglés, con grabacion de la respuesta y feedback.",
"P0::Buscador de empleo local (Chile): Puyal, LinkedIn, Computrabajo y BNE con alertas diarias emparejadas a las certificaciones del usuario.",
"P0::Benchmark salarial: rangos por puesto y ciudad (Chile) y remoto, con fuente y fecha, para fijar meta y evaluar ofertas.",
"P0::Postulacion directa: cada tarjeta 100% gratis lleva a la pagina real de postular (Apply Now) y rastrea el estado (postulado, confirmado, admitido).",
"P0::Recordatorios inteligentes por fechas reales (plazos, ventanas, examenes, renovaciones) con escala si se ignoran y 'lo hago ahora'.",
"P0::Busqueda en tiempo real v2: consulta en lenguaje natural ('cert cloud gratis con examen en menos de 3 meses') con respuesta estructurada y evidencia.",
"P0::Monitor de salud de enlaces: verificacion diaria automatica de todas las URLs del catalogo (status + texto clave) con alerta si mueren o cambia la condicion.",
"P0::Deteccion automatica de fuentes nuevas: escaneo semanal de programas gratis o con descuento (universidades, vendors, gobierno) con verificacion antes de incorporarlos.",
"P0::Verificacion anti-fantasma: toda oferta con nivel (oficial, prensa, comunidad), enlace a la evidencia y fecha de verificacion visible en la tarjeta.",
"P0::Gestion central del estatus estudiantil para aplicar a todos los beneficios de estudiante (AWS, Google, Microsoft, Databricks, IBM) con estado y vencimiento.",
"P0::Asistente de becas: paso a paso de cada beca (Coursera, edX, SENCE) con carta de postulacion borrador generada desde el perfil.",
"P0::SENCE local: cursos gratis con fechas y ventanas de postulación, alertas de apertura y postulación directa con ClaveUnica.",
"P0::Progreso con evidencia: reporte semanal (horas, simulacros, avance, badges) exportable a PDF, usable en entrevista como prueba de constancia.",
"P0::Motor de auto-mejora: la app audita sus propios enlaces, datos, rendimiento y UX, y propone/aplica mejoras con changelog visible.",
"P0::Retrospectiva semanal: cada domingo, pantalla 'que funciono, que falta, plan de la semana' generada desde datos reales.",
],
"S02": [
"Perfil con 'modo realista': si hay menos de 5 horas por semana, el plan solo usa micro-bloques y no castiga.",
"Importar CV o PDF para detectar las skills actuales y no recomendar lo que ya se domina.",
"Autoevaluacion por area (1 a 5) con mini-test por tipo de examen, para calibrar el punto de partida real.",
"Metas multiples: meta principal (empleo) + meta secundaria (cambio de area), cada una con su sub-plan.",
"Fotos de inicio: guardar el CV y el LinkedIn de hoy para medir el avance 'antes/despues' al final.",
"Perfil 100% local: sin cuenta, sin nube, exportable como JSON en un toque.",
"Si cambia la meta (por ejemplo ciber a datos), el roadmap se recalcula y conserva lo que sigue sirviendo.",
"Cambios explicitos: sin camara para examen, solo celular, internet limitado, zona horaria distinta.",
"Salario objetivo en CLP y en USD, con conversion y fuente visible.",
"Campo 'por que' (motivacion personal) que la app muestra en los dias dificeles.",
"Calendario familiar y de turnos: bloques que la app nunca ocupa (trabajo, familia, cursos presenciales).",
"Sincronizacion semanal de 2 minutos: la app pregunta 3 cosas (horas, energia, avance) y ajusta el plan.",
"Modo 'PRO en N meses': se fija la meta y el plan se invierte (que hacer cada semana hacia atras).",
"Perfil con 'modo estricto $0': oculta todo lo que cueste dinero, aunque sea barato.",
],
"S03": [
"Roadmap personal: secuencia ordenada de certificaciones del catalogo con hitos y semanas estimadas.",
"Cada hito con criterio de salida medible (simulacro en 80 o mas, proyecto entregado, postulacion enviada).",
"Prerrequisitos auto-detectados: si una cert exige conocimiento X, la ruta inserta antes la cert o curso que falta.",
"Tres rutas para el mismo objetivo: rapida, equilibrada y profunda, con diferencia de semanas y horas.",
"Visibilidad de sinergias: que certificaciones suman entre si (mismo vendor, mismo stack) para el CV.",
"Densidad maxima de carga por semana, con semanas buffer explicitas en el calendario.",
"Re-plan automatico si un hito se atrasa: recalcula fechas sin perder el progreso registrado.",
"'Lista de descarte': certificaciones que ya no encajan en la meta, con el motivo guardado.",
"Roadmap exportable a PDF para guardarlo, imprimirlo o mostrarlo a un mentor.",
"Puertas (gating): no se muestra la cert N+1 hasta completar N o marcarla explicitamente como saltada.",
"ROI por certificacion en la ruta: peso en el mercado local, costo (debe ser $0), tiempo y dificultad.",
"Integracion con SENCE: si un curso local gratis cubre un hito, la ruta lo propone como via principal.",
"Tres zooms del roadmap: por trimestre, por mes y por semana.",
"Hito 'contratetable': la semana en que el CV queda listo para postular, con checklist de paquete (CV, LinkedIn, portafolio).",
],
"S04": [
"Calendario de estudio con bloques realistas (commute, almuerzo) y re-agendado automatico si se salta uno.",
"Repaso espaciado: los errores de simulacros y las notas re-aparecen en intervalos 1, 3, 7 y 21 dias.",
"Recuerdo activo: antes de cada bloque, 5 preguntas sobre lo que se iba a estudiar.",
"Metodo por tipo de test: opcion multiple con banco de preguntas, laboratorio con sandbox, oral con simulador, portafolio con checklist.",
"Modo pomodoro con sonido local y sin internet.",
"Modo commute: lecciones de 15 a 20 minutos en audio o flashcards, solo con el telefono.",
"Notas de estudio por certificacion con busqueda y enlace a la fuente oficial de cada tema.",
"Deteccion de meseta: 3 semanas sin progreso cambia el metodo (de teorico a practico) y lo avisa.",
"Resumen diario de 10 minutos: que estudiar hoy y por que (basado en la fecha del examen).",
"Todo el material de estudio consolidado en una carpeta por cert (enlaces, PDF descargados, flashcards).",
"Estudio en paralelo de 2 certificaciones con intercalacion para evitar burnout.",
"Modo 'estudio minimo viable': si la semana se cae, queda solo lo imprescindible para mantener la fecha.",
"Packs de estudio offline por modulo, para descargar en dias de datos caros o lentos.",
"Contador semanal de horas con tendencia (subiendo, plana, cayendo) y alerta si cae dos semanas.",
],
"S05": [
"Motor de simulacros auto-generados a partir del temario (syllabus) oficial de cada certificacion.",
"Opcion multiple: feedback inmediato con explicacion y enlace a la fuente de cada pregunta.",
"Opcion multiple cronometrado: condiciones exactas del examen (tiempo, sin volver atras) con reporte por tema.",
"Laboratorio: guia paso a paso con sandbox (Docker o VM) y verificacion automatica del resultado de cada paso.",
"Defensa oral: simulador con preguntas en español e inglés y grabacion de la propia respuesta.",
"Portafolio: checklist de evidencias con rubrica auto-generada por item y seinal 'listo'.",
"Coding: ejercicios locales con autograder (tests) y diff contra la solucion de referencia.",
"Simulacion de incidente: escenario guiado con puntos de decision y postmortem al final.",
"Casos: caso de negocio con datos reales (CSV, BI) y preguntas abiertas con solucion modelo.",
"Simulacro con curva de dificultad (facil a dificil) y nivel adaptativo segun respuestas.",
"Bitacora global de errores por tema y por certificacion, con plan de repaso integrado.",
"Historial de puntajes con tendencia y seinal 'listo' (3 simulacros seguidos en 80 o mas).",
"Export de errores a Anki y a flashcards del telefono en un toque.",
"Regla dura: nunca se sirve un simulacro del tipo equivocado para la cert (usa el campo 'examen' del catalogo).",
],
"S06": [
"Asistente de dia de examen: checklist T-7, T-3, T-1 y T-0 (documentos, camara, software de proctoring, prueba de sistema).",
"Requisitos de proctoring auto-detectados por certificacion (OnVUE u otro) con enlace a la prueba de sistema.",
"'Prueba mi PC' local: camara, micro, internet, navegador y zona horaria, con lista de fallas.",
"Countdown en vivo al examen en portada y en widget.",
"Plan B: que hacer si el examen sale mal (politica de retake, descuento de retake, tiempos de espera).",
"Calendario de retakes: la app registra la fecha del retake y la protege en el plan.",
"Registro del resultado (aprobado o no, puntaje, fecha) con foto o PDF del certificado adjunto.",
"Postulacion de logro: al aprobar, la app genera la siguiente accion (subir a Credly, actualizar CV, LinkedIn).",
"Contingencia de proctoring: segundo dispositivo de respaldo, navegador alterno, numeros de soporte.",
"Rutina anti-ansiedad de 2 minutos antes del examen (respiracion + checklist).",
"'Paquete de examen' en un solo lugar: confirmacion, ID, temario, hojas permitidas.",
"Gestion de zona horaria: si el examen cae en otra zona, la alarma se pone en hora local (Chile).",
"Si el examen es oral o por proyecto: agendador con el evaluador y recordatorios mutuos.",
"Deteccion de descuento de retake (fuente oficial) y aplicacion automatica al plan.",
],
"S07": [
"Busqueda por lenguaje natural: 'cert cloud gratis con examen en menos de 3 meses' con respuesta estructurada.",
"Filtros combinables: tipo de examen, idioma, duracion, costo, modalidad, plazo, nivel, vendor.",
"Cada resultado con evidencia (cita textual de la pagina) y fecha de verificacion (anti-fantasma).",
"Busqueda profunda: scraping bajo demanda de la fuente con progreso visible y cache local.",
"'Que me encuentre': consultas guardadas que se re-ejecutan solas cada dia y avisan si hay novedades.",
"Busqueda semantica local del catalogo (embeddings) que funciona sin internet.",
"Busqueda por keywords del CV: 'que certificacion gratis me anade las skills que ya tengo'.",
"Respuesta con 'como postular en 3 pasos' para cada resultado.",
"Comparador de 2 o 3 ofertas: costo, tiempo, peso en el mercado, dificultad y tipo de examen.",
"Busqueda por voz en español (online u offline).",
"Ultimas busquedas con un toque para repetirlas.",
"Boton 'las 3 mejores para ti': top 3 ofertas segun el perfil, con el motivo de cada una.",
"Busqueda en el archivo de ofertas pasadas: que existio, que termino y que lo reemplazo.",
"Export de cualquier busqueda (JSON o CSV) con la evidencia completa.",
],
"S08": [
"Escáner de codigos de un solo uso con seinal 'esto solo se usa una vez' antes de consumirlo.",
"Verificacion de codigo antes de usar: confirmar que es valido en la pagina oficial antes de gastarlo.",
"Vouchers de estudiante: asistente central (AWS, Google, Microsoft, Databricks, IBM, Oracle) con estado de cada uno.",
"Estado de cada beneficio: aplicado, activo, vencido, con fecha y fuente oficial.",
"Dector de 'fugas': codigos que aparecen en la comunidad (Reddit, Discord) con nivel de riesgo y de verificacion.",
"Expiracion de codigos auto-detectada (texto de la pagina) y actualizacion del deadline en el calendario.",
"Copiar codigo en un toque, con contexto (donde usarlo, que paso, limite de uso).",
"Historial de codigos usados, para no re-utilizar uno de un solo uso por error.",
"Alerta de vouchers nuevos para el area del usuario (estudiante, residente, examen especifico).",
"'Pila de beneficios': combinar voucher oficial + estudiante + promo, verificando que sea combinable.",
"Deteccion de 'codigos falsos': patrones que parecen codigos y no lo son, con explicacion.",
"Escáner sobre pagina del usuario: pegar cualquier URL y extraer la oferta con evidencia.",
"Reporte semanal de codigos: que expiraron y que aparecieron nuevos, con fuente.",
"Nivel de verificacion de cada fuga: oficial, prensa o comunidad; nunca se presenta una fuga no verificada como oficial.",
],
}
