/* Certf — ARCHIVO GENERADO por tools/crawler.py (no editar a mano).
   La app lo lee para la pestaña Novedades y el sello de última revisión. */
window.__CERTF_NOVEDADES__ = {
 "checked": "2026-09-19T16:46:56Z",
 "items": [
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-19",
   "grupo": "agregador",
   "id": "370b16343a",
   "kind": "oferta",
   "lang": "EN",
   "name": "Class Central · credenciales gratis de Google",
   "review": false,
   "sig": "600freegooglecertificationstrendingmostcommonprojectmanagementharvardflutterpopularsubjectsengineering18815coursesartificialintelligence29215coursesgenerativeai",
   "src": "classcentral",
   "text": "600 Free Google Certifications Trending Most common project management harvard flutter Popular subjects Engineering 18,815 courses Artificial Intelligence 29,215 courses Generative AI 12,740 courses Popular courses AP® Microeconomics Massachusetts Institute of Technology Marketing Innovative Products and Services University of Maryland, College Park Gamification University of Pennsylvania Class Ce",
   "unico": false,
   "url": "https://www.classcentral.com/report/free-google-certifications/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-19",
   "grupo": "oficial",
   "id": "186f8d6487",
   "kind": "badge",
   "lang": "EN",
   "name": "GitHub · Student Developer Pack",
   "review": false,
   "sig": "tagssecurityanalyticsgethelpathoneybadgersupportpoeditoraboutpoeditorpoeditorisahighlyscalablelocalizationmanagementplatformforteams",
   "src": "github-pack",
   "text": "Tags Security & analytics Get help at Honeybadger support POEditor About POEditor POEditor is a highly scalable localization management platform for teams.",
   "unico": false,
   "url": "https://education.github.com/pack"
  },
  {
   "found": "2026-09-18",
   "id": "4b0042fdd6",
   "kind": "cambio",
   "name": "IBM SkillsBuild · credenciales Credly",
   "review": true,
   "sig": "cambio-71b7fd1a4eda",
   "src": "ibm-skillsbuild",
   "text": "La página cambió, pero no se detectó una oferta nueva legible. Revisa el enlace.",
   "url": "https://skillsbuild.org/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-18",
   "grupo": "oficial",
   "id": "0a9a21605e",
   "kind": "badge",
   "lang": "EN",
   "name": "GitHub · Student Developer Pack",
   "review": false,
   "sig": "tagssecurityanalyticsgethelpathoneybadgersupportpopsqlaboutpopsqlmoderncollaborativesqleditorforyourteamwritequeriesvisualizedataandshareyourresults",
   "src": "github-pack",
   "text": "Tags Security & analytics Get help at Honeybadger support PopSQL About PopSQL Modern, collaborative SQL editor for your team — write queries, visualize data, and share your results.",
   "unico": false,
   "url": "https://education.github.com/pack"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-16",
   "grupo": "badges",
   "id": "f6ac6643fd",
   "kind": "oferta",
   "lang": "EN",
   "name": "Salesforce Trailhead · superbadges",
   "review": false,
   "sig": "realworldpractice100freegethandsonexperienceinrealsalesforceenvironmentsasyousolvebusinessscenariosautomateworkflowsbuildaiagentsandextendsalesforceintothetools",
   "src": "trailhead",
   "text": "Real-world practice, 100% free Get hands-on experience in real Salesforce environments as you solve business scenarios, automate workflows, build AI agents, and extend Salesforce into the tools where people work.",
   "unico": false,
   "url": "https://trailhead.salesforce.com/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-16",
   "grupo": "badges",
   "id": "61d209a32f",
   "kind": "badge",
   "lang": "EN",
   "name": "Salesforce Trailhead · superbadges",
   "review": false,
   "sig": "credentialsthatproveyourexpertiseearnbadgesbuildaiexpertiseandpreparefor60officialsalesforcecertificationsthatvalidateyourskillsandhelpyoustandoutinthesalesforc",
   "src": "trailhead",
   "text": "Credentials that prove your expertise Earn badges, build AI expertise, and prepare for 60+ official Salesforce certifications that validate your skills and help you stand out in the Salesforce ecosystem.",
   "unico": false,
   "url": "https://trailhead.salesforce.com/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-16",
   "grupo": "oficial",
   "id": "534e96805f",
   "kind": "badge",
   "lang": "EN",
   "name": "GitHub · Student Developer Pack",
   "review": false,
   "sig": "tagssecurityanalyticsgethelpathoneybadgersupportdeepscanaboutdeepscandeepscanisaplatformforbuildingbetterandmorereliablejavascriptapps",
   "src": "github-pack",
   "text": "Tags Security & analytics Get help at Honeybadger support DeepScan About DeepScan DeepScan is a platform for building better and more reliable JavaScript apps.",
   "unico": false,
   "url": "https://education.github.com/pack"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-16",
   "grupo": "badges",
   "id": "27be6f9e2e",
   "kind": "oferta",
   "lang": "EN",
   "name": "Salesforce Trailhead · superbadges",
   "review": false,
   "sig": "buildsalesforceandaiskillslearnforfreewithhandsontrainingontrailhead",
   "src": "trailhead",
   "text": "Build Salesforce and AI Skills Learn for free with hands-on training on Trailhead.",
   "unico": false,
   "url": "https://trailhead.salesforce.com/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-15",
   "grupo": "oficial",
   "id": "f23709b8a3",
   "kind": "oferta",
   "lang": "EN",
   "name": "GitHub · Student Developer Pack",
   "review": false,
   "sig": "offersoffer6monthaccesstowebsitefirewallmalwarescannertagssecurityanalyticsgethelpatastrasecuritysupportcodecovaboutcodecovcodecovmakesiteasytoimplementcodecove",
   "src": "github-pack",
   "text": "Offers Offer 6 month access to website firewall & malware scanner Tags Security & analytics Get help at AstraSecurity support Codecov About Codecov Codecov makes it easy to implement code coverage to develop healthier code Offers Offer Free access to Codecov on public and private repositories.",
   "unico": false,
   "url": "https://education.github.com/pack"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-15",
   "grupo": "oficial",
   "id": "b608597558",
   "kind": "badge",
   "lang": "EN",
   "name": "GitHub · Student Developer Pack",
   "review": false,
   "sig": "tagssecurityanalyticsgethelpathoneybadgersupportdevcycleaboutdevcycledevcycleisafeatureflagmanagementplatformbuiltfordevelopers",
   "src": "github-pack",
   "text": "Tags Security & analytics Get help at Honeybadger support DevCycle About DevCycle DevCycle is a Feature Flag Management platform built for developers.",
   "unico": false,
   "url": "https://education.github.com/pack"
  },
  {
   "found": "2026-09-14",
   "id": "b451531a97",
   "kind": "cambio",
   "name": "Fundación Telefónica · Conecta Empleo",
   "review": true,
   "sig": "cambio-8e01b915da7b",
   "src": "telefonica",
   "text": "La página cambió, pero no se detectó una oferta nueva legible. Revisa el enlace.",
   "url": "https://conectaempleo.fundaciontelefonica.com/"
  },
  {
   "found": "2026-09-14",
   "id": "9cdd1573e5",
   "kind": "cambio",
   "name": "GitHub · Student Developer Pack",
   "review": true,
   "sig": "cambio-fb9eed43c70f",
   "src": "github-pack",
   "text": "La página cambió, pero no se detectó una oferta nueva legible. Revisa el enlace.",
   "url": "https://education.github.com/pack"
  },
  {
   "found": "2026-09-14",
   "id": "88935362c0",
   "kind": "cambio",
   "name": "Anthropic Academy · certificados gratis de IA",
   "review": true,
   "sig": "cambio-aa1b62b62316",
   "src": "anthropic",
   "text": "La página cambió, pero no se detectó una oferta nueva legible. Revisa el enlace.",
   "url": "https://anthropic.skilljar.com/"
  },
  {
   "found": "2026-09-13",
   "id": "fddce35bca",
   "kind": "cambio",
   "name": "Class Central · credenciales gratis de Google",
   "review": true,
   "sig": "cambio-81226be68a29",
   "src": "classcentral",
   "text": "La página cambió, pero no se detectó una oferta nueva legible. Revisa el enlace.",
   "url": "https://www.classcentral.com/report/free-google-certifications/"
  },
  {
   "found": "2026-09-13",
   "id": "c1c920f4c0",
   "kind": "cambio",
   "name": "dumpsgate · códigos AWS (agregador, no oficial)",
   "review": true,
   "sig": "cambio-e3b0c44298fc",
   "src": "dumpsgate",
   "text": "La página cambió, pero no se detectó una oferta nueva legible. Revisa el enlace.",
   "url": "https://dumpsgate.com/aws-promo-codes/"
  },
  {
   "found": "2026-09-13",
   "id": "76997a135e",
   "kind": "cambio",
   "name": "AWS · Código AIF2CLOUD (Pearson VUE)",
   "review": true,
   "sig": "cambio-b1ec0debbcb8",
   "src": "aws-aif2cloud",
   "text": "La página cambió, pero no se detectó una oferta nueva legible. Revisa el enlace.",
   "url": "https://www.pearsonvue.com/us/en/aws/aif2cloud.html"
  },
  {
   "found": "2026-09-13",
   "id": "719190c5ed",
   "kind": "cambio",
   "name": "Coursera · Google Cybersecurity Certificate",
   "review": true,
   "sig": "cambio-0ba8c79b4c4f",
   "src": "coursera-gcyber",
   "text": "La página cambió, pero no se detectó una oferta nueva legible. Revisa el enlace.",
   "url": "https://www.coursera.org/google-certificates/cybersecurity-certificate"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-13",
   "grupo": "oficial",
   "id": "56f8c7692e",
   "kind": "badge",
   "lang": "EN",
   "name": "GitHub · Student Developer Pack",
   "review": false,
   "sig": "tagsdevelopertoolsinfrastructureapisgethelpatpoeditorsupporthoneybadgerabouthoneybadgerthewebdeveloperssecretweaponexceptionuptimeandcronmonitoringthatssoawesom",
   "src": "github-pack",
   "text": "Tags Developer tools Infrastructure & APIs Get help at POEditor support Honeybadger About Honeybadger The web developer's secret weapon: exception, uptime, and cron monitoring that's so awesome, you'll wish your site had more errors.",
   "unico": false,
   "url": "https://education.github.com/pack"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "fd598b1637",
   "kind": "oferta",
   "lang": "ES",
   "name": "SENCE Chile · cursos gratis con certificado",
   "review": false,
   "sig": "senceymicrosoftabrentresnuevoscursosgratuitosparaampliarcompetenciasdigitalessencepasaralcontenidoprincipalpersonasempresasorganismossobresenceparticipacinciuda",
   "src": "sence-chile",
   "text": "Sence y Microsoft abren tres nuevos cursos gratuitos para ampliar competencias digitales | SENCE Pasar al contenido principal Personas Empresas Organismos Sobre Sence Participación ciudadana Personas (current) Empresas Organismos Sobre Sence Ingresar ayuda Participación ciudadana Inicio » Personas » Noticias Sence y Microsoft abren tres nuevos cursos gratuitos para ampliar competencias digitales L",
   "unico": false,
   "url": "https://sence.gob.cl/personas/noticias/sence-y-microsoft-abren-tres-nuevos-cursos-gratuitos-para-ampliar-competencias-digitales"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-12",
   "grupo": "comunidad",
   "id": "f3b6cceb9a",
   "kind": "oferta",
   "lang": "EN",
   "name": "Hacker News · 'free voucher' (últimas publicaciones)",
   "review": false,
   "sig": "query22freevoucher22certificationtagsstoryhitsperpage20advancedsyntaxtrueanalyticstagsbackend",
   "src": "hn-vouchers",
   "text": "query=%22free+voucher%22+certification&tags=story&hitsPerPage=20&advancedSyntax=true&analyticsTags=backend",
   "unico": false,
   "url": "https://hn.algolia.com/api/v1/search_by_date?query=%22free%20voucher%22%20certification&tags=story&hitsPerPage=20"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "f2a68672b8",
   "kind": "oferta",
   "lang": "ES/EN",
   "name": "Coursera · Google Cybersecurity Certificate",
   "review": false,
   "sig": "googlecybersecurityprofessionalcertificatecourseraforindividualsforbusinessesforuniversitiesforgovernmentsexploredegreesloginjoinforfreejoinforfreegooglecyberse",
   "src": "coursera-gcyber",
   "text": "Google Cybersecurity Professional Certificate | Coursera For Individuals For Businesses For Universities For Governments Explore Degrees ​ Log In Join for Free Join for Free Google Cybersecurity Professional Certificate About Outcomes Courses Testimonials Previous Next Browse Computer Science Computer Security and Networks Google Cybersecurity Professional Certificate Get on the fast track to a ca",
   "unico": false,
   "url": "https://www.coursera.org/google-certificates/cybersecurity-certificate"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "agregador",
   "id": "f1c51ab7c9",
   "kind": "oferta",
   "lang": "EN",
   "name": "Class Central · credenciales gratis de Google",
   "review": false,
   "sig": "coursereport450freegooglecertificationscoursesbadges2026googleoffers450freeonlinecourseswithcertificatesandbadgescoveringgoogleadsanalyticsaicloudandmore",
   "src": "classcentral",
   "text": "Course Report 450+ Free Google Certifications, Courses & Badges [2026] Google offers 450+ free online courses with certificates and badges, covering Google Ads, Analytics, AI, Cloud, and more.",
   "unico": false,
   "url": "https://www.classcentral.com/report/free-google-certifications/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-12",
   "grupo": "badges",
   "id": "f16bc11a89",
   "kind": "badge",
   "lang": "EN",
   "name": "Salesforce Trailhead · superbadges",
   "review": false,
   "sig": "trailheadthefunwaytolearnskiptomaincontenttrailheadmobilenavtoggledatamobilenavtargetbuttonhomelearndropdownhandlekeydownhiddengrowyoursalesforceexpertisebadges",
   "src": "trailhead",
   "text": "Trailhead | The fun way to learn Skip to main content Trailhead mobile-nav#toggle\" data-mobile-nav-target=\"button\"> Home Learn dropdown#handleKeydown\" hidden> Grow your Salesforce expertise Badges Gain new skills and hands-on experience through bite-sized units Trails Follow guided learning paths Trailhead Journeys Curated trails that build product expertise Superbadges Get hands-on applying your ",
   "unico": false,
   "url": "https://trailhead.salesforce.com/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "ef1cec4052",
   "kind": "oferta",
   "lang": "EN/ES",
   "name": "Universidad de Helsinki · Elements of AI",
   "review": false,
   "sig": "ourgoalistodemystifyaitheelementsofaiisaseriesoffreeonlinecoursescreatedbyminnalearnandtheuniversityofhelsinki",
   "src": "helsinki-ai",
   "text": "Our goal is to demystify AI The Elements of AI is a series of free online courses created by MinnaLearn and the University of Helsinki.",
   "unico": false,
   "url": "https://www.elementsofai.com"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [
    "AIF-C01",
    "CLF-C02"
   ],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "ea382b4822",
   "kind": "codigo",
   "lang": "EN",
   "name": "AWS · Código AIF2CLOUD (Pearson VUE)",
   "review": false,
   "sig": "intheeventyoufailtheaifc01examyouwillnotbeeligibleforthefreeclfc02exam",
   "src": "aws-aif2cloud",
   "text": "In the event you fail the AIF-C01 Exam, you will not be eligible for the free CLF-C02 Exam.",
   "unico": false,
   "url": "https://www.pearsonvue.com/us/en/aws/aif2cloud.html"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "e8d6d525f7",
   "kind": "oferta",
   "lang": "EN",
   "name": "Databricks · Training y Learning Festivals",
   "review": false,
   "sig": "viewalltrainingrequestprivatetrainingfreeondemandtrainingdatabricksfundamentalsinjustonehourlearnaboutthelatestdataandaitechniquesandhowtobringaitoyourdatawithd",
   "src": "databricks",
   "text": "View all training Request private training Free on-demand training Databricks Fundamentals In just one hour, learn about the latest data and AI techniques and how to bring AI to your data with Databricks.",
   "unico": false,
   "url": "https://www.databricks.com/training"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "badges",
   "id": "e87d59dbab",
   "kind": "oferta",
   "lang": "EN",
   "name": "Google Cloud Skills Boost · skill badges",
   "review": false,
   "sig": "jointhegearprogramandfuelyourcloudjourneywith35monthlycreditsforhandsonlearningingoogleskillsatnocosttoyou",
   "src": "gcp-skillsboost",
   "text": "Join the GEAR program and fuel your cloud journey with 35 monthly credits for hands-on learning in Google Skills, at no cost to you.",
   "unico": false,
   "url": "https://www.cloudskillsboost.google/"
  },
  {
   "badge": false,
   "beca": true,
   "codes": [],
   "disc": null,
   "etiqueta": "BECA / AYUDA",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "e591786442",
   "kind": "oferta",
   "lang": "ES",
   "name": "Fundación Telefónica · Conecta Empleo",
   "review": false,
   "sig": "fundacintelefnicaespaasaltaralcontenidoprincipalquhacemosquinessomosparticipaimpactoespaaesenquhacemoscomprometidosconeducacinformacinyempleobecascampus42recone",
   "src": "telefonica",
   "text": "Fundación Telefónica España Saltar al contenido principal Qué hacemos Quiénes somos Participa Impacto España ES EN Qué hacemos Comprometidos con Educación, Formación y Empleo Becas Campus 42 Reconectados ProFuturo OrientaHub Conciencia digital Voluntariado Telefónica Voluntariado Telefónica Campañas de donación Arte, Cultura y Pensamiento Informe Soberanía Digital Europa Premios Tecnológicos Espac",
   "unico": false,
   "url": "https://conectaempleo.fundaciontelefonica.com/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [
    "AIF-C01",
    "CLF-C02"
   ],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "agregador",
   "id": "e39ade3703",
   "kind": "codigo",
   "lang": "EN",
   "name": "dumpsgate · códigos AWS (agregador, no oficial)",
   "review": false,
   "sig": "200standardkeydeadlinesaifc01mustbetakenandpassedbyseptember3020261159pmlocalctforonlineclfc02freeexammustbecompletedbynovember302026restrictionsonepercustomera",
   "src": "dumpsgate",
   "text": "$200 standard) Key deadlines AIF-C01 must be taken and passed by September 30, 2026 (11:59 PM local / CT for online) CLF-C02 free exam must be completed by November 30, 2026 Restrictions One per customer/account; cannot be combined with other offers or vouchers Only valid on Pearson VUE.",
   "unico": false,
   "url": "https://dumpsgate.com/aws-promo-codes/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": 50,
   "etiqueta": "50% DESCUENTO",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "e00a93361a",
   "kind": "oferta",
   "lang": "EN",
   "name": "AWS · Página de certificaciones",
   "review": false,
   "sig": "youcanalsoaccessyourawscertifiedbenefitssuchasyourdigitalbadgeand50discountvoucherforafutureexam",
   "src": "aws-certification",
   "text": "You can also access your AWS Certified benefits, such as your digital badge and 50% discount voucher for a future exam.",
   "unico": false,
   "url": "https://aws.amazon.com/certification/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-12",
   "grupo": "badges",
   "id": "c5936efe32",
   "kind": "badge",
   "lang": "EN",
   "name": "IBM Cognitive Class · certificados y badges",
   "review": false,
   "sig": "learnmoredismissmeasurespaceclassheaderglobalbgwhiteshadowlgstickytop0z30searchallcourseslearningpathsguidedprojectsactivitiessigninregisteropenmainmenulearning",
   "src": "ibm-cognitive",
   "text": "Learn more → Dismiss measureSpace())\" class=\"header-global bg-white shadow-lg sticky top-0 z-30\"> Search All Courses Learning Paths Guided Projects Activities Sign in Register Open main menu Learning Paths Courses & Projects Badges Search All Courses Learning Paths Guided Projects Activities help#showHelp\" title=\"Help\" aria-label=\"Help\"> Learning Paths Courses & Projects Badges Sign in Register Le",
   "unico": false,
   "url": "https://cognitiveclass.ai/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "c25c7b4ead",
   "kind": "oferta",
   "lang": "EN",
   "name": "ISC2 · 1MCC (códigos gratuitos)",
   "review": false,
   "sig": "underexamsfindyourfreeccexamandclickschedule",
   "src": "isc2-1mcc",
   "text": "Under “ Exams ”, find your free CC exam and click “ Schedule ”.",
   "unico": false,
   "url": "https://www.isc2.org/1mcc"
  },
  {
   "badge": false,
   "beca": true,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "c1ebb3d1fa",
   "kind": "oferta",
   "lang": "ES",
   "name": "Santander Open Academy · becas y cursos gratis",
   "review": false,
   "sig": "comienzaaexplorarcomienzaaexplorarabiertohasta31122026sacapartidoalstorytellingenlaeradelmarketingdigitalcursodemarketingdigitalcontheuniversityofchicagomsinfor",
   "src": "santander",
   "text": "Comienza a explorar Comienza a explorar Abierto hasta 31/12/2026 Saca partido al storytelling en la era del marketing digital Curso de Marketing Digital con The University of Chicago Más información Más información Abierto hasta el 31/12/2025 La formación que necesitas para seguir creciendo Cursos, contenidos y becas, sin coste para ti.",
   "unico": false,
   "url": "https://www.santanderopenacademy.com/es"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "baad6f9aca",
   "kind": "oferta",
   "lang": "EN",
   "name": "AWS · Página de certificaciones",
   "review": false,
   "sig": "getstartedexamvouchersareyousupportingateamtakingawscertificationexams",
   "src": "aws-certification",
   "text": "Get started Exam Vouchers Are you supporting a team taking AWS Certification exams?",
   "unico": false,
   "url": "https://aws.amazon.com/certification/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "b310bde174",
   "kind": "oferta",
   "lang": "ES",
   "name": "Elements of AI en español",
   "review": false,
   "sig": "unaintroduccinalainteligenciaartificialenlneaygratisparanoexpertoselementsofaiempezarelcursobuildingaicomunidadonlinepreguntasfrecuenteselementsofaiempezarelcur",
   "src": "elementsofai-es",
   "text": "Una introducción a la inteligencia artificial, en línea y gratis, para no expertos Elements of AI Empezar el curso Building AI Comunidad online Preguntas frecuentes Elements of AI Empezar el curso Building AI Comunidad online Preguntas frecuentes België Belgique (français) Bulgaria Czech Danmark Deutschland Eesti Éire Ελλάδα España Global France Hrvatska Ireland Ísland Italia Latvija Lietuva Luxem",
   "unico": false,
   "url": "https://www.elementsofai.com/es"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "badges",
   "id": "a12f5275d7",
   "kind": "oferta",
   "lang": "EN",
   "name": "IBM SkillsBuild · credenciales Credly",
   "review": false,
   "sig": "whetheryourestartingyourcareerorpivotingtosomethingnewibmskillsbuildoffers100freelearningfromagloballeaderintechnologyandinnovation",
   "src": "ibm-skillsbuild",
   "text": "Whether you’re starting your career or pivoting to something new, IBM SkillsBuild offers 100% free learning from a global leader in technology and innovation.",
   "unico": false,
   "url": "https://skillsbuild.org/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [
    "AIF-C01",
    "AIF2CLOUD",
    "CLF-C02",
    "SAA-C03"
   ],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "agregador",
   "id": "9beabdd431",
   "kind": "codigo",
   "lang": "EN",
   "name": "dumpsgate · códigos AWS (agregador, no oficial)",
   "review": false,
   "sig": "recommendedpathcostoptimizedstepcertificationexamcoststrategy1awsaipractitioneraifc0110050usecodeaif2cloudvalidtosep302026passtounlockfreeclfc021bawscloudpracti",
   "src": "dumpsgate",
   "text": "Recommended Path (Cost-Optimized) Step Certification Exam Cost Strategy 1 AWS AI Practitioner ( AIF-C01 ) $100 → $50 Use code AIF2CLOUD (valid to Sep 30, 2026); pass to unlock free CLF-C02 1b AWS Cloud Practitioner ( CLF-C02 ) $100 → $0 Free after passing AIF-C01 with AIF2CLOUD code (must complete by Nov 30, 2026) 2 AWS Solutions Architect Associate ( SAA-C03 ) $150 Most widely held cert; strong R",
   "unico": false,
   "url": "https://dumpsgate.com/aws-promo-codes/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "97b5a7c58d",
   "kind": "oferta",
   "lang": "EN",
   "name": "AWS · Código AIF2CLOUD (Pearson VUE)",
   "review": false,
   "sig": "afterpassingtheawscertifiedaipractitionerexamthefreeattemptfortheawscertifiedcloudpractitionerwillbeautomaticallyappliedduringexamregistration",
   "src": "aws-aif2cloud",
   "text": "After passing the AWS Certified AI Practitioner Exam, the free attempt for the AWS Certified Cloud Practitioner will be automatically applied during exam registration.",
   "unico": false,
   "url": "https://www.pearsonvue.com/us/en/aws/aif2cloud.html"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "94c858575a",
   "kind": "oferta",
   "lang": "EN",
   "name": "ISC2 · 1MCC (códigos gratuitos)",
   "review": false,
   "sig": "learnmoreanunprecedentedsuccessinlessthanfouryears1millionpeopleenrolledintheprogramgainingfreeaccesstothecconlineselfpacedcertificationcourseandafreeccexam5700",
   "src": "isc2-1mcc",
   "text": "Learn More An Unprecedented Success In less than four years: 1 million+ people enrolled in the program, gaining free access to the CC Online Self-Paced certification course and a free CC exam 570,000+ participants took their CC course to learn foundational concepts of cybersecurity, enabling them to evaluate cybersecurity as a potential career 65,000+ individuals progressed through the program to ",
   "unico": false,
   "url": "https://www.isc2.org/1mcc"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "8ee5e70b56",
   "kind": "oferta",
   "lang": "ES",
   "name": "Elements of AI en español",
   "review": false,
   "sig": "nuestroobjetivoesdesmitificarlaiaelementosdelaiaesunaseriedecursosgratuitosenlneacreadosporminnalearnylauniversidaddehelsinki",
   "src": "elementsofai-es",
   "text": "Nuestro objetivo es desmitificar la IA Elementos de la IA es una serie de cursos gratuitos en línea creados por MinnaLearn y la Universidad de Helsinki.",
   "unico": false,
   "url": "https://www.elementsofai.com/es"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "8ce53dd529",
   "kind": "oferta",
   "lang": "EN",
   "name": "GitHub · Student Developer Pack",
   "review": false,
   "sig": "offersofferstudentscannowgetfreeordiscountedaccesstoourpowerfulproductivityappswithaibuiltin1tbofcloudstorageandandadvancedsecurityforyourdataanddevices",
   "src": "github-pack",
   "text": "Offers Offer Students can now get free or discounted access to our powerful productivity apps with AI built in, 1TB of cloud Storage, and and advanced security for your data and devices.",
   "unico": false,
   "url": "https://education.github.com/pack"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-12",
   "grupo": "badges",
   "id": "7658e169ac",
   "kind": "badge",
   "lang": "EN",
   "name": "Google Cloud Skills Boost · skill badges",
   "review": false,
   "sig": "exploreourskillbadgesandcertificates",
   "src": "gcp-skillsboost",
   "text": "Explore our Skill Badges and Certificates.",
   "unico": false,
   "url": "https://www.cloudskillsboost.google/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "6c8b3c276e",
   "kind": "oferta",
   "lang": "EN",
   "name": "Universidad de Helsinki · Full Stack Open",
   "review": false,
   "sig": "thecoursematerialislicensedundercreativecommonsbyncsa30licensewhichmeansthatyouarefreetouseanddistributethematerialaslongasthenamesoftheoriginalauthorsarenotrem",
   "src": "helsinki-fso",
   "text": "The course material is licensed under Creative Commons BY-NC-SA 3.0 license , which means that you are free to use and distribute the material, as long as the names of the original authors are not removed.",
   "unico": false,
   "url": "https://fullstackopen.com/en/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [
    "2022-25"
   ],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "68c6ba4ee9",
   "kind": "codigo",
   "lang": "ES",
   "name": "SENCE Chile · cursos gratis con certificado",
   "review": false,
   "sig": "senceymicrosoftabrentresnuevoscursosgratuitosparaampliarcompetenciasdigitalesgobiernotransparentesolicituddeinformacinpblicaanuarioestadsticosencepreviousnextso",
   "src": "sence-chile",
   "text": "Sence y Microsoft abren tres nuevos cursos gratuitos para ampliar competencias digitales Gobierno Transparente Solicitud de Información Pública Anuario Estadístico Sence Previous Next Solicitud Audiencias y Ley Lobby OIRS Regionales Ley de Presupuestos e instrucciones presuspuetarias Cierre Administrativo 2022-25 Comisión Mixta Prácticas Técnico-Profesionales Catálogo de Planes Formativos Chile At",
   "unico": false,
   "url": "https://sence.gob.cl/personas/noticias/sence-y-microsoft-abren-tres-nuevos-cursos-gratuitos-para-ampliar-competencias-digitales"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": null,
   "etiqueta": "",
   "found": "2026-09-12",
   "grupo": "badges",
   "id": "6175d47151",
   "kind": "badge",
   "lang": "EN",
   "name": "Salesforce Trailhead · superbadges",
   "review": false,
   "sig": "gamifiedplatformgetrewardedwithpointsandbadgeswhenyoulearnnewskills",
   "src": "trailhead",
   "text": "Gamified Platform Get rewarded with points and badges when you learn new skills.",
   "unico": false,
   "url": "https://trailhead.salesforce.com/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "agregador",
   "id": "5def643f89",
   "kind": "oferta",
   "lang": "EN",
   "name": "learnitfree.com · listado de certificaciones gratis",
   "review": false,
   "sig": "featuredanthropicaicertifications15completelyfreecertificationsfromthemakersofclaudeaiallwithverifiablecertificateswatchall15anthropiccertificationsin3minutescl",
   "src": "learnitfree",
   "text": "🤖 FEATURED: Anthropic AI Certifications 15 completely free certifications from the makers of Claude AI — all with verifiable certificates 📺 Watch: All 15 Anthropic Certifications in 3 Minutes 🤖 Claude 101 Beginner's guide to collaborating with Claude AI.",
   "unico": false,
   "url": "https://learnitfree.com/certifications/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "4c0391fee5",
   "kind": "oferta",
   "lang": "ES",
   "name": "Microsoft Learn · credenciales en español",
   "review": false,
   "sig": "renovacinmantengasuscertificacionesyaptitudesaldasincostoalgunoparaquesiempreseaeladecuadoparaeltrabajo",
   "src": "ms-learn-es",
   "text": "Renovación Mantenga sus certificaciones y aptitudes al día sin costo alguno, para que siempre sea el adecuado para el trabajo.",
   "unico": false,
   "url": "https://learn.microsoft.com/es-es/credentials/"
  },
  {
   "badge": false,
   "beca": true,
   "codes": [],
   "disc": null,
   "etiqueta": "BECA / AYUDA",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "466c555b3a",
   "kind": "oferta",
   "lang": "ES",
   "name": "Fundación Telefónica · Conecta Empleo",
   "review": false,
   "sig": "newsletterseleccionarpasbrasilespaamxicovenezuelapasidiomamenquhacemoscomprometidosconeducacinformacinyempleobecascampus42reconectadosprofuturoorientahubconcien",
   "src": "telefonica",
   "text": "Newsletter Seleccionar país Brasil España México Venezuela País / Idioma Menú Qué hacemos Comprometidos con Educación, Formación y Empleo Becas Campus 42 Reconectados ProFuturo OrientaHub Conciencia digital Destacado Lanzamos nuestro programa de becas Abrimos nuevas piscinas en 42.",
   "unico": false,
   "url": "https://conectaempleo.fundaciontelefonica.com/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "badges",
   "id": "4190fe32a8",
   "kind": "oferta",
   "lang": "EN",
   "name": "AWS · Skill Builder Digital Badges",
   "review": false,
   "sig": "awstrainingbadgesofferthesebenefitsdemonstrateyourprogressgainingknowledgeandskillsforspecificawscloudtopicssuchasserverlessshareableonsocialnetworkstohelpyoust",
   "src": "aws-badges",
   "text": "AWS Training badges offer these benefits: Demonstrate your progress gaining knowledge and skills for specific AWS Cloud topics, such as Serverless Shareable on social networks to help you stand out to recruiters and prospective hiring managers Free to earn and share How to earn an AWS Training Badge 1 1.",
   "unico": false,
   "url": "https://aws.amazon.com/training/badges/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "agregador",
   "id": "3d6092b5e4",
   "kind": "oferta",
   "lang": "EN",
   "name": "Class Central · credenciales gratis de Google",
   "review": false,
   "sig": "600freegooglecertificationstrendingmostcommonjavadatasciencemachinelearningpopularsubjectsdataanalysis9768coursescybersecurity28222coursesprogramming35602course",
   "src": "classcentral",
   "text": "600 Free Google Certifications Trending Most common java data science machine learning Popular subjects Data Analysis 9,768 courses Cybersecurity 28,222 courses Programming 35,602 courses Popular courses Introducción a la genética y la evolución Universidad Autónoma de Madrid Making Successful Decisions through the Strategy, Law & Ethics Model University of Michigan Academic Writing H.N.B Garhwal ",
   "unico": false,
   "url": "https://www.classcentral.com/report/free-google-certifications/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "3d5540d13b",
   "kind": "oferta",
   "lang": "EN",
   "name": "GitHub · Student Developer Pack",
   "review": false,
   "sig": "tagsdomainsvirtualeventsgethelpatnamecheapsupportmicrosoftazureaboutmicrosoftazureaccesstomicrosoftazurecloudservicesandlearningresourcesnocreditcardrequiredoff",
   "src": "github-pack",
   "text": "Tags Domains Virtual Events Get help at Namecheap support Microsoft Azure About Microsoft Azure Access to Microsoft Azure cloud services and learning resources – no credit card required Offers Offer Free access to 25+ Microsoft Azure cloud services plus $100 in Azure credit.",
   "unico": false,
   "url": "https://education.github.com/pack"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "3a6477737e",
   "kind": "oferta",
   "lang": "ES",
   "name": "Santander Open Academy · becas y cursos gratis",
   "review": false,
   "sig": "formacinyaprendizajeonlinesantanderopenacademyreproduccinautomticadelcarouselhaymuchoscaminosparacrecerencuentraeltuyoaccedegratisseasclientedesantanderono",
   "src": "santander",
   "text": "Formación y aprendizaje online | Santander Open Academy Reproducción automática del carousel Hay muchos caminos para crecer, encuentra el tuyo Accede gratis, seas cliente de Santander o no.",
   "unico": false,
   "url": "https://www.santanderopenacademy.com/es"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "agregador",
   "id": "32f7cdc4f2",
   "kind": "oferta",
   "lang": "EN",
   "name": "learnitfree.com · listado de certificaciones gratis",
   "review": false,
   "sig": "2000freeitcertificationsbadgeslearnitfree2000freecertificationsbadgesgetcertifiedbygoogleibmmicrosoftharvardanthropic20topproviderscompletelyfreein2026nocreditc",
   "src": "learnitfree",
   "text": "2000+ Free IT Certifications & Badges | Learn IT Free 🏆 2000+ Free Certifications & Badges Get certified by Google, IBM, Microsoft, Harvard, Anthropic & 20+ top providers — Completely FREE in 2026 ✅ No Credit Card 📜 Instant Certificates 🚀 Career Boost 🤖 15 Free Anthropic Certs 2000+ Free Certificates 20+ Top Providers 100% Free Forever NEW Anthropic 15 Certs All Categories 🤖 AI/ML ☁️ Cloud 🔐 Secur",
   "unico": false,
   "url": "https://learnitfree.com/certifications/"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "3058be32a8",
   "kind": "oferta",
   "lang": "EN",
   "name": "Databricks · Training y Learning Festivals",
   "review": false,
   "sig": "free1h30mfreeondemandtrainingaiagentfundamentalsaiagentsempowerteamstoworksmarterautomateeverydaytasksanddriveinnovation",
   "src": "databricks",
   "text": "FREE 1H 30M Free on-demand training AI Agent Fundamentals AI agents empower teams to work smarter, automate everyday tasks and drive innovation.",
   "unico": false,
   "url": "https://www.databricks.com/training"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "es",
   "id": "291ad95b62",
   "kind": "oferta",
   "lang": "ES",
   "name": "Microsoft Learn · credenciales en español",
   "review": false,
   "sig": "renovablerenuevelascertificacioneselegiblesanualmentesincostocompletandounabreveevaluacinenlnea",
   "src": "ms-learn-es",
   "text": "Renovable: renueve las certificaciones elegibles anualmente sin costo completando una breve evaluación en línea.",
   "unico": false,
   "url": "https://learn.microsoft.com/es-es/credentials/"
  },
  {
   "badge": true,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "badges",
   "id": "1cec66f8dc",
   "kind": "oferta",
   "lang": "EN",
   "name": "AWS · Skill Builder Digital Badges",
   "review": false,
   "sig": "thereisnocosttocreateacredlycomaccountoracceptabadge",
   "src": "aws-badges",
   "text": "there is no cost to create a Credly.com account or accept a badge.",
   "unico": false,
   "url": "https://aws.amazon.com/training/badges/"
  },
  {
   "badge": false,
   "beca": true,
   "codes": [],
   "disc": null,
   "etiqueta": "BECA / AYUDA",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "18cae487ba",
   "kind": "oferta",
   "lang": "ES/EN",
   "name": "Coursera · Google Cybersecurity Certificate",
   "review": false,
   "sig": "becauseofthiscybersecurityanalystsareinhighdemandandcancommandacompetitivesalaryacrossawiderangeofindustries",
   "src": "coursera-gcyber",
   "text": "Because of this, cybersecurity analysts are in high demand and can command a competitive salary across a wide range of industries.",
   "unico": false,
   "url": "https://www.coursera.org/google-certificates/cybersecurity-certificate"
  },
  {
   "badge": false,
   "beca": false,
   "codes": [],
   "disc": 100,
   "etiqueta": "100% GRATIS",
   "found": "2026-09-12",
   "grupo": "oficial",
   "id": "07ce8bff5d",
   "kind": "oferta",
   "lang": "EN/ES",
   "name": "Universidad de Helsinki · Elements of AI",
   "review": false,
   "sig": "welcometotheelementsofaifreeonlinecourse",
   "src": "helsinki-ai",
   "text": "Welcome to the Elements of AI free online course!",
   "unico": false,
   "url": "https://www.elementsofai.com"
  },
  {
   "found": "2026-09-11",
   "id": "852c83ca0d",
   "kind": "oferta",
   "name": "AWS · Código AIF2CLOUD (Pearson VUE)",
   "review": false,
   "sig": "usethepromocodetoget50offawscertifiedaipractitioner",
   "src": "aws-aif2cloud",
   "text": "Use the promo code to get 50% off AWS Certified AI Practitioner.",
   "url": "https://www.pearsonvue.com/us/en/aws/aif2cloud.html"
  },
  {
   "found": "2026-09-11",
   "id": "633f2ed34d",
   "kind": "oferta",
   "name": "AWS · Código AIF2CLOUD (Pearson VUE)",
   "review": false,
   "sig": "passtheawscertifiedaipractitionerexambyseptember30andyoullqualifyforafreeawscertifiedcloudpractitionerexamanytimebeforenovember302026",
   "src": "aws-aif2cloud",
   "text": "Pass the AWS Certified AI Practitioner exam by September 30, and you'll qualify for a free AWS Certified Cloud Practitioner exam any time before November 30, 2026.",
   "url": "https://www.pearsonvue.com/us/en/aws/aif2cloud.html"
  }
 ]
};
